name: Clang Format Checker
on: 
  push:
      branches: [Stage1-Testing]
  pull_request:
      branches: [Stage1-Testing]

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "**/*.hpp,**/*.cpp"
