name: Doxygen implementation

on:
  push:
    branches: [Stage1-Testing]
  pull_request:
    branches: [Stage1-Testing]

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: '.'
          doxyfile-path: './Doxyfile'
