name: Doxygen implementation

  push:
      branches:
        - Stage1-Testing
  pull-request:
      branches:
        - Stage1-Testing

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'ECS/'
        working-directory: 'Game/'
        working-directory: 'Server/'
        doxyfile-path: './Doxyfile'